### ISSUE TITLE
GUI connectivity [1]

### ISSUE THREAD

**Issue by prajogt** [CSC207-2022F-UofT/course-project-group-72#40]
Using clean architecture and therefore presenters and viewmodels, connect different views by updating the screen
- Login -> Home
- Home -> Restaurant (via Search)
- Home -> Profile
- Profile -> Reviews/Restaurants
- Restaurant -> Review
- Restaurant -> Available Interactions
- Review -> Available Interactions

**Comment by foreverwoods** [comment]
Possible Edit:

Login -> Home
Home -> **Filtered Restaurants** (via Search)
**Filtered Restaurants** -> Restaurant

**Comment by prajogt** [comment]
With this, have all the required screens implement IFrame, and pass themselves through when creating a new view

**Comment by foreverwoods** [comment]
Updated Connectivity:

WelcomeScreenView (Login/Register) **->** HomeScreenView (Search/Sort) **->** ChoicesSortedView (Filtered Restaurants)

Need to bridge connection between ChoicesSortedView and RestaurantView.

**Comment by foreverwoods** [comment]
Updated Connectivity:

WelcomeScreenView (Login/Register) -> HomeScreenView (Search/Sort) -> ChoicesSortedView (Filtered Restaurants)
-> ViewRestaurant -> Review Restaurant

**Comment by prajogt** [comment]
Completed with IFrame and ViewInterface updates.
