### ISSUE TITLE
[Feature 6] <Profile System>

### ISSUE THREAD

**Issue by foreverwoods** [CSC207-2022F-UofT/course-project-group-72#6]
Each User has a Customer profile which every User can access. Accessing this page would require the press of a button, which is either: 
- the top right of the window to access your own profile
- clicking on another user while looking at their review

This action would create a new window of the chosen Customer's Profile Page which shows their average star rating as a customer as well as their past reviews.
Lead: @davatana

**Comment by Allof02** [comment]
Close with pr#110
