### ISSUE TITLE
[Feature 7] <Home Screen View>

### ISSUE THREAD

**Issue by foreverwoods** [CSC207-2022F-UofT/course-project-group-72#7]
The Home Screen in which the User should be able to return to (once logged-in).
This screen displays the Searching Component found in Feature 3, Restaurant Search System.

**Leads:** Janssen & David
Janssen: Implement User's input/filter selections and the transition from HomeScreenView -> Filtered Restaurants 
David: Implement the universal HomeScreen button that can be found on every screen.

**Comment by foreverwoods** [comment]
**EDIT** Thurs, Nov 17th, this issue was initially designed for everyone to each implement a home button for their views, but since David will implement a universal button, I have limited the Assignees.

**Comment by Allof02** [comment]
Closed with PR #86
